version: "2.2"
services: 
  zentao:
    image: idoop/zentao:latest
    container_name: zentao
    # if web response code: 310 ERR_TOO_MANY_REDIRECTS, please use host mode.
#    network_mode: "host"
    ports:
      - "80:80"
      - "3306:3306"
    # mysql root account default password is '123456'.
    # the zentao adminstrator account is 'admin',and init password is '123456'.
    environment:
    # specifies Adminer account and password for web login database.
      USER: "root"
      PASSWD: "123456"
      BIND_ADDRESS: "false"
    extra_hosts:
      - "smtp.exmail.qq.com:163.177.90.125"
    volumes:
      - ./data:/opt/zbox/
    restart: always
